name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -race -v . ./sasl ./driver ./internal/data -coverprofile coverage.out

    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        file: coverage.out

  smoketest:
    name: Smoke Test
    runs-on: ubuntu-latest
    services:
      zoo1:
        image: zookeeper
        ports:
          - 2181:2181
        env:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

      zoo2:
        image: zookeeper
        ports:
          - 2182:2181
        env:
          ZOO_MY_ID: 2
          ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

      zoo3:
        image: zookeeper
        ports:
          - 2183:2181
        env:
          ZOO_MY_ID: 3
          ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

    steps:
      - name: Checkout code into the directory
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk

      - name: Get and Startup Drill
        run: |
          sudo mkdir /opt/drill
          sudo sh -c 'wget -O - http://apache.mirrors.hoobly.com/drill/drill-1.17.0/apache-drill-1.17.0.tar.gz | tar -xzC /opt'
          sudo mv /opt/apache-drill-1.17.0/* /opt/drill
          sudo cp smoketest/storage-plugins-override.conf /opt/drill/conf/
          sudo cp smoketest/drill-override.conf /opt/drill/conf/drill-override.conf
          sudo /opt/drill/bin/drillbit.sh --config /opt/drill/conf start

      # - name: Start up the stack
      #   run: cd smoketest && docker-compose up -d

      # - name: Add drill ref as localhost
      #   run: sudo sh -c "echo '127.0.0.1 drill' >> /etc/hosts"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Run smoke test
        run: go test -race -v -tags smoke . -run ^Example$

      - name: print drill log
        if: ${{ failure() }}
        run: cat /opt/drill/log/drillbit.log /opt/drill/log/drillbit.out

      - name: Stop drillbit
        run: sudo /opt/drill/bin/drillbit.sh graceful_stop
